/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Badge: typeof import('./src/components/global/Badge.vue')['default']
    CodeGroupItem: typeof import('./src/components/global/CodeGroupItem.vue')['default']
    DelayTeleport: typeof import('./src/components/DelayTeleport.vue')['default']
    Github: typeof import('./src/components/icons/Github.vue')['default']
    Home: typeof import('./src/components/Home.vue')['default']
    Ins: typeof import('./src/components/icons/Ins.vue')['default']
    ListNotes: typeof import('./src/components/ListNotes.vue')['default']
    ListPosts: typeof import('./src/components/ListPosts.vue')['default']
    MaterialSymbolsFavorite: typeof import('./src/components/icons/MaterialSymbolsFavorite.vue')['default']
    Moon: typeof import('./src/components/icons/Moon.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    NewContent: typeof import('./src/components/NewContent.vue')['default']
    NewListNotes: typeof import('./src/components/NewListNotes.vue')['default']
    NewNavBar: typeof import('./src/components/NewNavBar.vue')['default']
    NewPost: typeof import('./src/components/NewPost.vue')['default']
    OperationPanel: typeof import('./src/components/OperationPanel.vue')['default']
    Plum: typeof import('./src/components/Plum.vue')['default']
    Post: typeof import('./src/components/Post.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sun: typeof import('./src/components/icons/Sun.vue')['default']
  }
}
