/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Github: typeof import('./src/components/icons/Github.vue')['default']
    Home: typeof import('./src/components/Home.vue')['default']
    Ins: typeof import('./src/components/icons/Ins.vue')['default']
    Moon: typeof import('./src/components/icons/Moon.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    Plum: typeof import('./src/components/Plum.vue')['default']
    Post: typeof import('./src/components/Post.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sun: typeof import('./src/components/icons/Sun.vue')['default']
  }
}
